### ISSUE TITLE
Cannot find module 'log4js'

### ISSUE THREAD

**Issue by hopewise** [awslabs/amazon-kinesis-client-nodejs#20]
After npm install, I tried to run the producer, I got this error:

```
Error: Cannot find module 'log4js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/samples/util/logger.js:18:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

So, what's wrong?

**Comment by selvavalluvan** [comment]
try "npm install log4js" separately. Your package.json might be missing the dependency.

**Comment by Sahilmaxi** [comment]
yes, it worked !
