### ISSUE TITLE
missing java class when attempting to kick off the consumer in clickstream sample

### ISSUE THREAD

**Issue by superpan** [awslabs/amazon-kinesis-client-nodejs#3]
Getting the following errors when executing the consumer in clickstream sample.

```
vagrant@vagrant:~/amazon-kinesis-client-nodejs/samples/click_stream_sample/consumer$ ~/amazon-kinesis-client-nodejs/bin/kcl-bootstrap --java /usr/bin/java -p ./sample.properties -e
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/commons-codec-1.3.jar downloaded. 9 files remain.
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/joda-time-2.4.jar downloaded. 8 files remain.
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/aws-java-sdk-1.7.13.jar downloaded. 7 files remain.
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/jackson-databind-2.1.1.jar downloaded. 6 files remain.
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/commons-logging-1.1.1.jar downloaded. 5 files remain.
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/amazon-kinesis-client-1.2.0.jar downloaded. 4 files remain.
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/jackson-core-2.1.1.jar downloaded. 3 files remain.
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/httpclient-4.2.jar downloaded. 2 files remain.
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/httpcore-4.2.jar downloaded. 1 files remain.
/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/jackson-annotations-2.1.1.jar downloaded. 0 files remain.
==========================================================
/usr/bin/java -cp /home/vagrant/amazon-kinesis-client-nodejs/lib/jars/amazon-kinesis-client-1.2.0.jar:/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/aws-java-sdk-1.7.13.jar:/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/commons-codec-1.3.jar:/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/commons-logging-1.1.1.jar:/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/httpclient-4.2.jar:/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/httpcore-4.2.jar:/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/jackson-annotations-2.1.1.jar:/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/jackson-core-2.1.1.jar:/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/jackson-databind-2.1.1.jar:/home/vagrant/amazon-kinesis-client-nodejs/lib/jars/joda-time-2.4.jar:/home/vagrant/amazon-kinesis-client-nodejs/samples/click_stream_sample/consumer:/home/vagrant/amazon-kinesis-client-nodejs/samples/click_stream_sample/consumer com.amazonaws.services.kinesis.multilang.MultiLangDaemon ./sample.properties
==========================================================
Starting Multi-Lang Daemon ...
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentialsProvider
	at com.amazonaws.services.kinesis.clientlibrary.config.KinesisClientLibConfigurator.<init>(KinesisClientLibConfigurator.java:63)
	at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.main(MultiLangDaemon.java:197)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentialsProvider
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 2 more
```

**Comment by superpan** [comment]
nm, figured it out.

**Comment by uwaseem** [comment]
Sorry for commenting on a closed issue, but I'm getting the same exact error. Mind sharing how you managed to solve this? Thanks !!

**Comment by schematical** [comment]
@superpan how did you fix?
