### ISSUE TITLE
run consumer as background service

### ISSUE THREAD

**Issue by junaidnasir** [awslabs/amazon-kinesis-client-nodejs#32]
I have been trying to use it as background service on ubuntu 16.06. absolute paths gives exception
` /home/ubuntu/kcl/bin/kcl-bootstrap --java /usr/bin/java -e -p /home/ubuntu/kcl/samples/basic_sample/consumer/sample.properties -s
`
results in
```
Starting Multi-Lang Daemon ...
Exception in thread "main" java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Properties.java:434)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:341)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.loadProperties(MultiLangDaemonConfig.java:135)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:85)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:70)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:57)
```

also tried with `/etc/init.d/` and changed directory to `consumer` folder and ran `../../../bin/kcl-bootstrap --java /usr/bin/java -e -p ./sample.properties -s`

is there any way I can run it as background service (relaunch if it crashes and start on boot)
thanks for any help

**Comment by pfifer** [comment]
A couple of questions:
* What version of the Node.js client are you using
* Can you provide the output of /usr/bin/java -version

**Comment by junaidnasir** [comment]
```
$ node --version
v7.4.0

$ /usr/bin/java -version
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
