### ISSUE TITLE
Java error `java.lang.NoClassDefFoundError` after upgrading from `2.2.5` to `2.2.6`

### ISSUE THREAD

**Issue by stekycz** [awslabs/amazon-kinesis-client-nodejs#344]
I am trying to update the library to the latest version but I am getting the following error.

```sh
Starting MultiLangDaemon ...
java.lang.NoClassDefFoundError: software/amazon/awssdk/identity/spi/IdentityProvider
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at software.amazon.kinesis.multilang.config.MultiLangDaemonConfiguration.<init>(MultiLangDaemonConfiguration.java:250)
        at software.amazon.kinesis.multilang.config.KinesisClientLibConfigurator.<init>(KinesisClientLibConfigurator.java:50)
        at software.amazon.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:81)
        at software.amazon.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:65)
        at software.amazon.kinesis.multilang.MultiLangDaemon.buildMultiLangDaemonConfig(MultiLangDaemon.java:171)
        at software.amazon.kinesis.multilang.MultiLangDaemon.main(MultiLangDaemon.java:220)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.identity.spi.IdentityProvider
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 15 more
software/amazon/awssdk/identity/spi/IdentityProvider
Usage: amazon-kinesis-client MultiLangDaemon [options]
  Options:
    -l, --log-configuration
      File location of logback.xml to be override the default
    -p, --properties-file
      Properties file to be used with the KCL

For more information, visit: https://github.com/awslabs/amazon-kinesis-client
```

I have cleared all jars I had before and all latest versions are downloaded. When I leave the older versions of Java dependencies in place (in the jars directory) it works. However, I do not want to mix multiple versions of the same dependency as that does not feel right.

**Comment by stekycz** [comment]
Updating `amazon-kinesis-client` to the latest version and all related Java dependencies accordingly may help IMO.
