### ISSUE TITLE
Unable to use KCL for nodejs v2.2.6 in java 1.8

### ISSUE THREAD

**Issue by saranarcot** [awslabs/amazon-kinesis-client-nodejs#365]
Here is my java version (1.8.0_422)

![image](https://github.com/user-attachments/assets/db8f5fa8-9e7a-4ab8-9a6c-8f12f0ff0f75)

I tried to use the KCL for nodejs v2.2.6  (https://github.com/awslabs/amazon-kinesis-client-nodejs/releases/tag/v2.2.6). But the **\samples\basic_sample\consumer\kcl-bootstrap** doesn't work fine and fails to start up. But it works fine in java 11. But as per the documentaiton it says, it should work fine with java 1.8 or above. Could anyone confirm what is the version of java supported for 

Logs: 
==========================================================
Starting MultiLangDaemon ...
==========================================================
Starting MultiLangDaemon ...
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/core/joran/spi/JoranException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/core/joran/spi/JoranException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/core/joran/spi/JoranException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3076)
        at java.lang.Class.getMethod0(Class.java:3046)
        at java.lang.Class.getMethod(Class.java:1812)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:670)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:652)

**Comment by higoramp** [comment]
Same problem here, @saranarcot you was able to fix this issue using the java 1.8?
